FROM ubuntu:22.04

# 환경 변수 설정
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# 패키지 리스트 업데이트 및 필요한 소프트웨어 설치
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless && \
    apt-get install -y maven gradle && \
    apt-get clean

# 포트 8080 열기 (Spring Boot 기본 포트)
EXPOSE 8080
